### ISSUE TITLE
Analise de tecnologias a serem usadas - backend

### ISSUE THREAD

**Issue by diogolabres** [diogolabres/teacher-betina#4]
Analisar qual tecnologia será utilizada no backend, qual versão da linguagem

**Comment by diogolabres** [comment]
Decidi usar Java para o backend, pois levará algum tempo para que todos aprendam Kotlin, e assim, fica mais fácil para novos membros começarem a desenvolver no app.

**Comment by GabsGear** [comment]
Você pode usar Kotlin e chamar as bibliotecas nativas do Java para ter o melhor dos dois mundos.

**Comment by diogolabres** [comment]
Vou ver como faz o generics no Kotlin pra poder trocar o código.

**Comment by diogolabres** [comment]
Vai ser Kotlin!
